language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
env:
  - CI=false
script:
  - yarn run lint
  - yarn run build
deploy:
  provider: heroku
  api_key:
    secure: $heroku_token
  app: osd-sidekick-app
  on:
    repo: open-source-developers/front-end
    branch: master
