name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
        name: ESLint
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Chromatic Action
        uses: chromaui/action@v1
        with:
          appCode: mjh42s87odq
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: yarn install, build, and test
        run: |
          yarn run lint
          yarn run build
        env:
          CI: true
