name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000
      - name: ESLint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm run lint
          npm run test
          npm run build
        env:
          CI: true
